version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: MySong
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      MONGO_URI: ${MONGO_URI}
      KKBOX_CLIENT_ID: ${KKBOX_CLIENT_ID}
      KKBOX_CLIENT_SECRET: ${KKBOX_CLIENT_SECRET}
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      SESSION_SECRET: ${SESSION_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_NAME: ${ADMIN_NAME}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongodb
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: myNginx
    depends_on:
      - web
    ports:
      - "80:80"
  mongodb:
    image: mongo:latest
    container_name: myMongoDB
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
