version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: MySong
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    container_name: myNginx
    depends_on:
      - web
    ports:
      - "80:80"
