version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: MySong
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongodb
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    container_name: myNginx
    depends_on:
      - web
    ports:
      - "80:80"
  mongodb:
    image: mongo:latest
    container_name: myMongoDB
    ports:
      - "27017:27017"
    env_file: .env
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
